modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
issueTrackerURL=""

[[mods]]
  modId="orespawn"
  version="0.1.0"
  displayName="Orespawn Revival (Scaffold)"
  description='''Port scaffold providing dimensions, basic registries, and placeholder entities to prevent crashes.'''

[[dependencies.orespawn]]
  modId="forge"
  mandatory=true
  versionRange="[47,)"
  ordering="NONE"
  side="BOTH"
[[dependencies.orespawn]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.20.1]"
  ordering="NONE"
  side="BOTH"

[[mods]]
  modId="dragonmounts"
  version="0.1.0"
  displayName="Dragon Mounts (Scaffold)"
  description='''Port scaffold registering placeholder dragon and egg items (no custom models yet).'''

[[dependencies.dragonmounts]]
  modId="forge"
  mandatory=true
  versionRange="[47,)"
  ordering="NONE"
  side="BOTH"
[[dependencies.dragonmounts]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.20.1]"
  ordering="NONE"
  side="BOTH"
