// 
// Decompiled by Procyon v0.5.36
// 

package danger.orespawn;

public class OreSpawnConstants
{
    public static int OREBLOCK_START_OFFSET;
    public static int NUMBER_OF_OREBLOCKS;
    public static int SpiderBlockID;
    public static int BatBlockID;
    public static int CowBlockID;
    public static int PigBlockID;
    public static int SquidBlockID;
    public static int ChickenBlockID;
    public static int CreeperBlockID;
    public static int SkeletonBlockID;
    public static int ZombieBlockID;
    public static int SlimeBlockID;
    public static int GhastBlockID;
    public static int ZombiePigmanBlockID;
    public static int EndermanBlockID;
    public static int CaveSpiderBlockID;
    public static int SilverfishBlockID;
    public static int MagmaCubeBlockID;
    public static int WitchBlockID;
    public static int SheepBlockID;
    public static int WolfBlockID;
    public static int MooshroomBlockID;
    public static int OcelotBlockID;
    public static int BlazeBlockID;
    public static int WitherSkeletonBlockID;
    public static int EnderDragonBlockID;
    public static int SnowGolemBlockID;
    public static int IronGolemBlockID;
    public static int WitherBossBlockID;
    public static int GirlfriendBlockID;
    public static int RedCowBlockID;
    public static int GoldCowBlockID;
    public static int EnchantedCowBlockID;
    public static int MOTHRABlockID;
    public static int AloBlockID;
    public static int CryoBlockID;
    public static int CamaBlockID;
    public static int VeloBlockID;
    public static int HydroBlockID;
    public static int BasilBlockID;
    public static int DragonflyBlockID;
    public static int EmperorScorpionBlockID;
    public static int ScorpionBlockID;
    public static int CaveFisherBlockID;
    public static int SpyroBlockID;
    public static int BaryonyxBlockID;
    public static int GammaMetroidBlockID;
    public static int CockateilBlockID;
    public static int KyuubiBlockID;
    public static int AlienBlockID;
    public static int AttackSquidBlockID;
    public static int WaterDragonBlockID;
    public static int KrakenBlockID;
    public static int LizardBlockID;
    public static int CephadromeBlockID;
    public static int DragonBlockID;
    public static int BeeBlockID;
    public static int HorseBlockID;
    public static int TrooperBugBlockID;
    public static int SpitBugBlockID;
    public static int StinkBugBlockID;
    public static int OstrichBlockID;
    public static int GazelleBlockID;
    public static int ChipmunkBlockID;
    public static int CreepingHorrorBlockID;
    public static int TerribleTerrorBlockID;
    public static int CliffRacerBlockID;
    public static int TriffidBlockID;
    public static int PitchBlackBlockID;
    public static int LurkingTerrorBlockID;
    public static int GodzillaPartBlockID;
    public static int SmallWormBlockID;
    public static int MediumWormBlockID;
    public static int LargeWormBlockID;
    public static int CassowaryBlockID;
    public static int CloudSharkBlockID;
    public static int GoldFishBlockID;
    public static int LeafMonsterBlockID;
    public static int TshirtBlockID;
    public static int EnderKnightBlockID;
    public static int EnderReaperBlockID;
    public static int BeaverBlockID;
    public static int TRexBlockID;
    public static int HerculesBlockID;
    public static int MantisBlockID;
    public static int StinkyBlockID;
    public static int BoyfriendBlockID;
    public static int TheKingPartBlockID;
    public static int EasterBunnyBlockID;
    public static int CaterKillerBlockID;
    public static int MolenoidBlockID;
    public static int SeaMonsterBlockID;
    public static int SeaViperBlockID;
    public static int LeonBlockID;
    public static int HammerheadBlockID;
    public static int RubberDuckyBlockID;
    public static int VillagerBlockID;
    public static int CriminalBlockID;
    public static int TheQueenPartBlockID;
    public static int OreSaltBlockID;
    public static int UraniumBlockID;
    public static int TitaniumBlockID;
    public static int OreAmethystBlockID;
    public static int OreRubyBlockID;
    public static int RTPBlockID;
    public static int LavafoamBlockID;
    public static int BlockUraniumBlockID;
    public static int BlockTitaniumBlockID;
    public static int BlockRubyBlockID;
    public static int BlockAmethystBlockID;
    public static int EnderPearlBlockID;
    public static int EyeOfEnderBlockID;
    public static int SkyTreeLogBlockID;
    public static int DuplicatorLogBlockID;
    public static int AntBlockID;
    public static int RedAntBlockID;
    public static int RainbowAntBlockID;
    public static int UnstableAntBlockID;
    public static int GodzillaBlockID;
    public static int TermiteBlockID;
    public static int CrystalTermiteBlockID;
    public static int TheKingBlockID;
    public static int MoleDirtBlockID;
    public static int BlockMobzillaScaleBlockID;
    public static int TheQueenBlockID;
    public static int AppleLeavesBlockID;
    public static int ExperienceLeavesBlockID;
    public static int LeavesScaryID;
    public static int StrawberryPlantBlockID;
    public static int FireflyPlantBlockID;
    public static int ButterflyPlantBlockID;
    public static int MothPlantBlockID;
    public static int MosquitoPlantBlockID;
    public static int ExperiencePlantBlockID;
    public static int FlowerPinkID;
    public static int FlowerBlueID;
    public static int FlowerBlackID;
    public static int FlowerScaryID;
    public static int CornPlant1BlockID;
    public static int CornPlant2BlockID;
    public static int CornPlant3BlockID;
    public static int CornPlant4BlockID;
    public static int TomatoPlant1BlockID;
    public static int TomatoPlant2BlockID;
    public static int TomatoPlant3BlockID;
    public static int TomatoPlant4BlockID;
    public static int LettucePlant1BlockID;
    public static int LettucePlant2BlockID;
    public static int LettucePlant3BlockID;
    public static int LettucePlant4BlockID;
    public static int RadishPlantBlockID;
    public static int LeavesCherryID;
    public static int LeavesPeachID;
    public static int RicePlantBlockID;
    public static int QuinoaPlant1BlockID;
    public static int QuinoaPlant2BlockID;
    public static int QuinoaPlant3BlockID;
    public static int QuinoaPlant4BlockID;
    public static int KrakenRepellentBlockID;
    public static int CreeperRepellentBlockID;
    public static int ExtremeTorchBlockID;
    public static int IslandBlockID;
    public static int PizzaBlockID;
    public static int KingSpawnerBlockID;
    public static int DungeonSpawnerBlockID;
    public static int QueenSpawnerBlockID;
    public static int DuctTapeBlockID;
    public static int CrystalStoneBlockID;
    public static int CrystalCoalBlockID;
    public static int CrystalGrassBlockID;
    public static int CrystalFlowerRedBlockID;
    public static int CrystalFlowerGreenBlockID;
    public static int CrystalFlowerBlueBlockID;
    public static int CrystalFlowerYellowBlockID;
    public static int CrystalTreeLogBlockID;
    public static int CrystalTreeLeavesBlockID;
    public static int CrystalCrystalBlockID;
    public static int CrystalPlanksBlockID;
    public static int CrystalWorkbenchBlockID;
    public static int CrystalFurnaceBlockID;
    public static int CrystalFurnaceBlockOnID;
    public static int CrystalTorchBlockID;
    public static int CrystalTreeLeaves2BlockID;
    public static int CrystalPinkBlockBlockID;
    public static int TigersEyeBlockID;
    public static int TigersEyeBlockBlockID;
    public static int CrystalRatBlockID;
    public static int CrystalFairyBlockID;
    public static int CrystalTreeLeaves3BlockID;
    public static int CrystalPlantBlockID;
    public static int CrystalPlant2BlockID;
    public static int CrystalPlant3BlockID;
    public static int RedAntTrollBlockID;
    public static int TermiteTrollBlockID;
    public static int CRYSTAL_OREBLOCK_START_OFFSET;
    public static int CRYSTAL_NUMBER_OF_OREBLOCKS;
    public static int UrchinBlockID;
    public static int FlounderBlockID;
    public static int SkateBlockID;
    public static int RotatorBlockID;
    public static int PeacockBlockID;
    public static int FairyBlockID;
    public static int DungeonBeastBlockID;
    public static int VortexBlockID;
    public static int RatBlockID;
    public static int WhaleBlockID;
    public static int IrukandjiBlockID;
    public static int CrystalCowBlockID;
    public static int OREBLOCK_START_OFFSET_TWO;
    public static int NUMBER_OF_OREBLOCKS_TWO;
    public static int BrutalflyBlockID;
    public static int NastysaurusBlockID;
    public static int PointysaurusBlockID;
    public static int CricketBlockID;
    public static int FrogBlockID;
    public static int SpiderDriverBlockID;
    public static int CrabBlockID;
    public static int EmptyCageItemID;
    public static int SpiderCageItemID;
    public static int BatCageItemID;
    public static int CowCageItemID;
    public static int PigCageItemID;
    public static int SquidCageItemID;
    public static int ChickenCageItemID;
    public static int CreeperCageItemID;
    public static int SkeletonCageItemID;
    public static int ZombieCageItemID;
    public static int SlimeCageItemID;
    public static int GhastCageItemID;
    public static int ZombiePigmanCageItemID;
    public static int EndermanCageItemID;
    public static int CaveSpiderCageItemID;
    public static int SilverfishCageItemID;
    public static int MagmaCubeCageItemID;
    public static int WitchCageItemID;
    public static int SheepCageItemID;
    public static int WolfCageItemID;
    public static int MooshroomCageItemID;
    public static int OcelotCageItemID;
    public static int BlazeCageItemID;
    public static int GirlfriendCageItemID;
    public static int WitherSkeletonCageItemID;
    public static int EnderDragonCageItemID;
    public static int SnowGolemCageItemID;
    public static int IronGolemCageItemID;
    public static int WitherBossCageItemID;
    public static int RedCowCageItemID;
    public static int GoldCowCageItemID;
    public static int EnchantedCowCageItemID;
    public static int MOTHRACageItemID;
    public static int AloCageItemID;
    public static int CryoCageItemID;
    public static int CamaCageItemID;
    public static int VeloCageItemID;
    public static int HydroCageItemID;
    public static int BasilCageItemID;
    public static int DragonflyCageItemID;
    public static int ScorpionCageItemID;
    public static int EmperorScorpionCageItemID;
    public static int SpyroCageItemID;
    public static int BaryonyxCageItemID;
    public static int GammaMetroidCageItemID;
    public static int CaveFisherCageItemID;
    public static int CockateilCageItemID;
    public static int KyuubiCageItemID;
    public static int AlienCageItemID;
    public static int AttackSquidCageItemID;
    public static int WaterDragonCageItemID;
    public static int KrakenCageItemID;
    public static int LizardCageItemID;
    public static int CephadromeCageItemID;
    public static int DragonCageItemID;
    public static int BeeCageItemID;
    public static int HorseCageItemID;
    public static int FireflyCageItemID;
    public static int ChipmunkCageItemID;
    public static int GazelleCageItemID;
    public static int OstrichCageItemID;
    public static int TrooperCageItemID;
    public static int SpitCageItemID;
    public static int StinkCageItemID;
    public static int CreepingHorrorCageItemID;
    public static int TerribleTerrorCageItemID;
    public static int CliffRacerCageItemID;
    public static int TriffidCageItemID;
    public static int PitchBlackCageItemID;
    public static int LurkingTerrorCageItemID;
    public static int WormSmallCageItemID;
    public static int WormMediumCageItemID;
    public static int WormLargeCageItemID;
    public static int CassowaryCageItemID;
    public static int CloudSharkCageItemID;
    public static int GoldFishCageItemID;
    public static int LeafMonsterCageItemID;
    public static int EnderKnightCageItemID;
    public static int EnderReaperCageItemID;
    public static int BeaverCageItemID;
    public static int UrchinCageItemID;
    public static int FlounderCageItemID;
    public static int SkateCageItemID;
    public static int RotatorCageItemID;
    public static int PeacockCageItemID;
    public static int FairyCageItemID;
    public static int DungeonBeastCageItemID;
    public static int VortexCageItemID;
    public static int RatCageItemID;
    public static int WhaleCageItemID;
    public static int IrukandjiCageItemID;
    public static int TRexCageItemID;
    public static int HerculesCageItemID;
    public static int MantisCageItemID;
    public static int StinkyCageItemID;
    public static int BoyfriendCageItemID;
    public static int EasterBunnyCageItemID;
    public static int CaterKillerCageItemID;
    public static int MolenoidCageItemID;
    public static int SeaMonsterCageItemID;
    public static int WitherSkeletonEggItemID;
    public static int EnderDragonEggItemID;
    public static int SnowGolemEggItemID;
    public static int IronGolemEggItemID;
    public static int WitherBossEggItemID;
    public static int GirlfriendEggItemID;
    public static int RedCowEggItemID;
    public static int GoldCowEggItemID;
    public static int EnchantedCowEggItemID;
    public static int MOTHRAEggItemID;
    public static int AloEggItemID;
    public static int CryoEggItemID;
    public static int CamaEggItemID;
    public static int VeloEggItemID;
    public static int HydroEggItemID;
    public static int BasilEggItemID;
    public static int DragonflyEggItemID;
    public static int EmperorScorpionEggItemID;
    public static int ScorpionEggItemID;
    public static int CaveFisherEggItemID;
    public static int SpyroEggItemID;
    public static int BaryonyxEggItemID;
    public static int GammaMetroidEggItemID;
    public static int CockateilEggItemID;
    public static int KyuubiEggItemID;
    public static int AlienEggItemID;
    public static int AttackSquidEggItemID;
    public static int WaterDragonEggItemID;
    public static int KrakenEggItemID;
    public static int LizardEggItemID;
    public static int CephadromeEggItemID;
    public static int DragonEggItemID;
    public static int BeeEggItemID;
    public static int TrooperEggItemID;
    public static int SpitEggItemID;
    public static int StinkEggItemID;
    public static int OstrichEggItemID;
    public static int GazelleEggItemID;
    public static int ChipmunkEggItemID;
    public static int CreepingHorrorEggItemID;
    public static int TerribleTerrorEggItemID;
    public static int CliffRacerEggItemID;
    public static int TriffidEggItemID;
    public static int PitchBlackEggItemID;
    public static int LurkingTerrorEggItemID;
    public static int GodzillaEggItemID;
    public static int SmallWormEggItemID;
    public static int MediumWormEggItemID;
    public static int LargeWormEggItemID;
    public static int CassowaryEggItemID;
    public static int UraniumNuggetItemID;
    public static int TitaniumNuggetItemID;
    public static int UraniumIngotItemID;
    public static int TitaniumIngotItemID;
    public static int GreenGooItemID;
    public static int DeadStinkBugItemID;
    public static int MothScaleItemID;
    public static int LavaEelItemID;
    public static int NightmareScaleItemID;
    public static int EmperorScorpionScaleItemID;
    public static int BasiliskScaleItemID;
    public static int WaterDragonScaleItemID;
    public static int JumpyBugScaleItemID;
    public static int KrakenToothItemID;
    public static int GodzillaScaleItemID;
    public static int CloudSharkEggItemID;
    public static int GoldFishEggItemID;
    public static int LeafMonsterEggItemID;
    public static int TshirtEggItemID;
    public static int EnderKnightEggItemID;
    public static int EnderReaperEggItemID;
    public static int BeaverEggItemID;
    public static int Robot5EggItemID;
    public static int CoinEggItemID;
    public static int SeaViperCageItemID;
    public static int FireFishItemID;
    public static int SunFishItemID;
    public static int SparkFishItemID;
    public static int SaltItemID;
    public static int PopcornItemID;
    public static int ButteredPopcornItemID;
    public static int ButteredSaltedPopcornItemID;
    public static int PopcornBagItemID;
    public static int ButterItemID;
    public static int StrawberryItemID;
    public static int CornCobItemID;
    public static int CornDogItemID;
    public static int RawCornDogItemID;
    public static int ButterCandyItemID;
    public static int BaconItemID;
    public static int RawBaconItemID;
    public static int GreenFishItemID;
    public static int BlueFishItemID;
    public static int PinkFishItemID;
    public static int RockFishItemID;
    public static int WoodFishItemID;
    public static int GreyFishItemID;
    public static int TomatoItemID;
    public static int LettuceItemID;
    public static int RadishItemID;
    public static int SaladItemID;
    public static int BLTItemID;
    public static int CherryItemID;
    public static int PeachItemID;
    public static int PizzaItemID;
    public static int CheeseItemID;
    public static int RawPeacockItemID;
    public static int PeacockItemID;
    public static int CrystalAppleItemID;
    public static int RiceItemID;
    public static int StrawberrySeedItemID;
    public static int AppleSeedItemID;
    public static int ButterflySeedItemID;
    public static int MothSeedItemID;
    public static int MosquitoSeedItemID;
    public static int FireflySeedItemID;
    public static int ExperienceTreeSeedItemID;
    public static int CherrySeedItemID;
    public static int PeachSeedItemID;
    public static int RotatorEggItemID;
    public static int PeacockEggItemID;
    public static int FairyEggItemID;
    public static int DungeonBeastEggItemID;
    public static int VortexEggItemID;
    public static int QuinoaItemID;
    public static int TRexEggItemID;
    public static int HerculesEggItemID;
    public static int MantisEggItemID;
    public static int StinkyEggItemID;
    public static int ZooKeeperItemID;
    public static int StepUpItemID;
    public static int StepDownItemID;
    public static int StepAccrossItemID;
    public static int ElevatorItemID;
    public static int MagicAppleItemID;
    public static int MinersDreamItemID;
    public static int ExperienceCatcherItemID;
    public static int IceBallItemID;
    public static int ThunderStaffItemID;
    public static int PoisonSwordItemID;
    public static int LaserBallItemID;
    public static int RayGunItemID;
    public static int WaterBallItemID;
    public static int UltimateArrowItemID;
    public static int SunspotUrchinItemID;
    public static int AcidItemID;
    public static int RedHeelsItemID;
    public static int BlackHeelsItemID;
    public static int SlippersItemID;
    public static int BootsItemID;
    public static int CreeperLauncherItemID;
    public static int NetherLostItemID;
    public static int CrystalSticksItemID;
    public static int PeacockFeatherItemID;
    public static int RatSwordItemID;
    public static int FairySwordItemID;
    public static int IrukandjiItemID;
    public static int GameControllerItemID;
    public static int AmethystItemID;
    public static int AmethystSwordItemID;
    public static int AmethystPickaxeItemID;
    public static int AmethystShovelItemID;
    public static int AmethystHoeItemID;
    public static int AmethystAxeItemID;
    public static int AmethystHelmetItemID;
    public static int AmethystBodyItemID;
    public static int AmethystLegsItemID;
    public static int AmethystBootsItemID;
    public static int RubyItemID;
    public static int RubySwordItemID;
    public static int RubyPickaxeItemID;
    public static int RubyShovelItemID;
    public static int RubyHoeItemID;
    public static int RubyAxeItemID;
    public static int RubyHelmetItemID;
    public static int RubyBodyItemID;
    public static int RubyLegsItemID;
    public static int RubyBootsItemID;
    public static int EmeraldSwordItemID;
    public static int EmeraldPickaxeItemID;
    public static int EmeraldShovelItemID;
    public static int EmeraldHoeItemID;
    public static int EmeraldAxeItemID;
    public static int EmeraldHelmetItemID;
    public static int EmeraldBodyItemID;
    public static int EmeraldLegsItemID;
    public static int EmeraldBootsItemID;
    public static int ExperienceSwordItemID;
    public static int ExperienceHelmetItemID;
    public static int ExperienceBodyItemID;
    public static int ExperienceLegsItemID;
    public static int ExperienceBootsItemID;
    public static int MothScaleHelmetItemID;
    public static int MothScaleBodyItemID;
    public static int MothScaleLegsItemID;
    public static int MothScaleBootsItemID;
    public static int LavaEelHelmetItemID;
    public static int LavaEelBodyItemID;
    public static int LavaEelLegsItemID;
    public static int LavaEelBootsItemID;
    public static int UltimateSwordItemID;
    public static int UltimateBowItemID;
    public static int UltimateFishingRodItemID;
    public static int UltimatePickaxeItemID;
    public static int UltimateShovelItemID;
    public static int UltimateHoeItemID;
    public static int UltimateAxeItemID;
    public static int UltimateHelmetItemID;
    public static int UltimateBodyItemID;
    public static int UltimateLegsItemID;
    public static int UltimateBootsItemID;
    public static int BerthaItemID;
    public static int SliceItemID;
    public static int MantisClawItemID;
    public static int BigHammerItemID;
    public static int SquidZookaItemID;
    public static int RoyalItemID;
    public static int HammyItemID;
    public static int ZooCage2ItemID;
    public static int ZooCage4ItemID;
    public static int ZooCage6ItemID;
    public static int ZooCage8ItemID;
    public static int ZooCage10ItemID;
    public static int SifterItemID;
    public static int NightmareSwordItemID;
    public static int InstantShelterItemID;
    public static int InstantGardenItemID;
    public static int CrystalWoodSwordItemID;
    public static int CrystalWoodPickaxeItemID;
    public static int CrystalWoodShovelItemID;
    public static int CrystalWoodHoeItemID;
    public static int CrystalWoodAxeItemID;
    public static int CrystalPinkSwordItemID;
    public static int CrystalPinkPickaxeItemID;
    public static int CrystalPinkShovelItemID;
    public static int CrystalPinkHoeItemID;
    public static int CrystalPinkAxeItemID;
    public static int CrystalStoneSwordItemID;
    public static int CrystalStonePickaxeItemID;
    public static int CrystalStoneShovelItemID;
    public static int CrystalStoneHoeItemID;
    public static int CrystalStoneAxeItemID;
    public static int CrystalPinkHelmetItemID;
    public static int CrystalPinkBodyItemID;
    public static int CrystalPinkLegsItemID;
    public static int CrystalPinkBootsItemID;
    public static int CrystalPinkIngotItemID;
    public static int TigersEyeSwordItemID;
    public static int TigersEyePickaxeItemID;
    public static int TigersEyeShovelItemID;
    public static int TigersEyeHoeItemID;
    public static int TigersEyeAxeItemID;
    public static int TigersEyeHelmetItemID;
    public static int TigersEyeBodyItemID;
    public static int TigersEyeLegsItemID;
    public static int TigersEyeBootsItemID;
    public static int TigersEyeIngotItemID;
    public static int PeacockFeatherHelmetItemID;
    public static int PeacockFeatherBodyItemID;
    public static int PeacockFeatherLegsItemID;
    public static int PeacockFeatherBootsItemID;
    public static int IrukandjiArrowItemID;
    public static int SkateBowItemID;
    public static int RatEggItemID;
    public static int FlounderEggItemID;
    public static int WhaleEggItemID;
    public static int IrukandjiEggItemID;
    public static int SkateEggItemID;
    public static int UrchinEggItemID;
    public static int Robot1EggItemID;
    public static int Robot2EggItemID;
    public static int Robot3EggItemID;
    public static int Robot4EggItemID;
    public static int GhostEggItemID;
    public static int GhostSkellyEggItemID;
    public static int BrownAntEggItemID;
    public static int RedAntEggItemID;
    public static int RainbowAntEggItemID;
    public static int UnstableAntEggItemID;
    public static int TermiteEggItemID;
    public static int ButterflyEggItemID;
    public static int MothEggItemID;
    public static int MosquitoEggItemID;
    public static int FireflyEggItemID;
    public static int MobzillaHelmetItemID;
    public static int MobzillaBodyItemID;
    public static int MobzillaLegsItemID;
    public static int MobzillaBootsItemID;
    public static int BoyfriendEggItemID;
    public static int TheKingEggItemID;
    public static int ThePrinceEggItemID;
    public static int RoyalHelmetItemID;
    public static int RoyalBodyItemID;
    public static int RoyalLegsItemID;
    public static int RoyalBootsItemID;
    public static int BerthaHandleItemID;
    public static int BerthaGuardItemID;
    public static int BerthaBladeItemID;
    public static int MolenoidNoseItemID;
    public static int SeaMonsterScaleItemID;
    public static int WormToothItemID;
    public static int TRexToothItemID;
    public static int CaterKillerJawItemID;
    public static int SeaViperTongueItemID;
    public static int VortexEyeItemID;
    public static int EasterBunnyEggItemID;
    public static int MolenoidEggItemID;
    public static int SeaMonsterEggItemID;
    public static int SeaViperEggItemID;
    public static int CaterKillerEggItemID;
    public static int RandomDungeonItemID;
    public static int BattleAxeItemID;
    public static int LeonCageItemID;
    public static int LeonEggItemID;
    public static int HammerheadCageItemID;
    public static int HammerheadEggItemID;
    public static int RubberDuckyCageItemID;
    public static int RubberDuckyEggItemID;
    public static int CrystalCowCageItemID;
    public static int VillagerCageItemID;
    public static int CrystalCowEggItemID;
    public static int VillagerEggItemID;
    public static int CriminalCageItemID;
    public static int CriminalEggItemID;
    public static int RockItemID;
    public static int RockSmallItemID;
    public static int RockRedItemID;
    public static int RockGreenItemID;
    public static int RockBlueItemID;
    public static int RockPurpleItemID;
    public static int RockSpikeyItemID;
    public static int RockTNTItemID;
    public static int RockCrystalRedItemID;
    public static int RockCrystalGreenItemID;
    public static int RockCrystalBlueItemID;
    public static int RockCrystalTNTItemID;
    public static int ChainsawItemID;
    public static int TheQueenEggItemID;
    public static int LapisHelmetItemID;
    public static int LapisBodyItemID;
    public static int LapisLegsItemID;
    public static int LapisBootsItemID;
    public static int QueenScaleItemID;
    public static int QueenHelmetItemID;
    public static int QueenBodyItemID;
    public static int QueenLegsItemID;
    public static int QueenBootsItemID;
    public static int DuctTapeItemID;
    public static int BrutalflyEggItemID;
    public static int NastysaurusEggItemID;
    public static int PointysaurusEggItemID;
    public static int CricketEggItemID;
    public static int ThePrincessEggItemID;
    public static int FrogEggItemID;
    public static int BrutalflyCageItemID;
    public static int NastysaurusCageItemID;
    public static int PointysaurusCageItemID;
    public static int CricketCageItemID;
    public static int FrogCageItemID;
    public static int QueenBattleAxeItemID;
    public static int SpiderRobotKitItemID;
    public static int WrenchItemID;
    public static int AntRobotKitItemID;
    public static int JefferyEggItemID;
    public static int AntRobotEggItemID;
    public static int SpiderRobotEggItemID;
    public static int SpiderDriverEggItemID;
    public static int SpiderDriverCageItemID;
    public static int RawCrabMeatItemID;
    public static int CrabMeatItemID;
    public static int CrabbyPattyItemID;
    public static int CrabEggItemID;
    public static int CrabCageItemID;
    public static int RoseSwordItemID;
    public static int LoveItemID;
    public static int SHOE_START_INDEX;
    public static int NUMBER_OF_SHOES;
    public static int RedHeelsIndex;
    public static int BlackHeelsIndex;
    public static int SlippersIndex;
    public static int BootsIndex;
    public static int GameControllerIndex;
    public static int WaterBallIndex;
    public static int SunspotUrchinIndex;
    public static int InkSackIndex;
    public static int LaserBallIndex;
    public static int IceBallIndex;
    public static int AcidIndex;
    public static int IrukandjiIndex;
    public static int EasterBunnyCageIndex;
    public static int CaterKillerCageIndex;
    public static int MolenoidCageIndex;
    public static int SeaMonsterCageIndex;
    public static int SeaViperCageIndex;
    public static int EmptyCageIndex;
    public static int SpiderCageIndex;
    public static int BatCageIndex;
    public static int CowCageIndex;
    public static int PigCageIndex;
    public static int SquidCageIndex;
    public static int ChickenCageIndex;
    public static int CreeperCageIndex;
    public static int SkeletonCageIndex;
    public static int ZombieCageIndex;
    public static int SlimeCageIndex;
    public static int GhastCageIndex;
    public static int ZombiePigmanCageIndex;
    public static int EndermanCageIndex;
    public static int CaveSpiderCageIndex;
    public static int SilverfishCageIndex;
    public static int MagmaCubeCageIndex;
    public static int WitchCageIndex;
    public static int SheepCageIndex;
    public static int WolfCageIndex;
    public static int MooshroomCageIndex;
    public static int OcelotCageIndex;
    public static int BlazeCageIndex;
    public static int GirlfriendCageIndex;
    public static int EnderDragonCageIndex;
    public static int SnowGolemCageIndex;
    public static int IronGolemCageIndex;
    public static int WitherBossCageIndex;
    public static int WitherSkeletonCageIndex;
    public static int RedCowCageIndex;
    public static int GoldCowCageIndex;
    public static int EnchantedCowCageIndex;
    public static int MOTHRACageIndex;
    public static int AloCageIndex;
    public static int CryoCageIndex;
    public static int CamaCageIndex;
    public static int VeloCageIndex;
    public static int HydroCageIndex;
    public static int BasilCageIndex;
    public static int BoyfriendCageIndex;
    public static int CrystalCowCageIndex;
    public static int VillagerCageIndex;
    public static int CriminalCageIndex;
    public static int WitherSkeletonEggIndex;
    public static int EnderDragonEggIndex;
    public static int SnowGolemEggIndex;
    public static int IronGolemEggIndex;
    public static int WitherBossEggIndex;
    public static int GirlfriendEggIndex;
    public static int RedCowEggIndex;
    public static int GoldCowEggIndex;
    public static int EnchantedCowEggIndex;
    public static int MOTHRAEggIndex;
    public static int AloEggIndex;
    public static int CryoEggIndex;
    public static int CamaEggIndex;
    public static int VeloEggIndex;
    public static int HydroEggIndex;
    public static int BasilEggIndex;
    public static int DragonflyCageIndex;
    public static int DragonflyEggIndex;
    public static int EmperorScorpionCageIndex;
    public static int EmperorScorpionEggIndex;
    public static int ScorpionCageIndex;
    public static int ScorpionEggIndex;
    public static int CaveFisherCageIndex;
    public static int CaveFisherEggIndex;
    public static int SpyroCageIndex;
    public static int SpyroEggIndex;
    public static int BaryonyxCageIndex;
    public static int BaryonyxEggIndex;
    public static int GammaMetroidCageIndex;
    public static int GammaMetroidEggIndex;
    public static int CockateilCageIndex;
    public static int CockateilEggIndex;
    public static int KyuubiCageIndex;
    public static int KyuubiEggIndex;
    public static int AlienCageIndex;
    public static int AlienEggIndex;
    public static int AttackSquidCageIndex;
    public static int AttackSquidEggIndex;
    public static int WaterDragonCageIndex;
    public static int WaterDragonEggIndex;
    public static int KrakenCageIndex;
    public static int KrakenEggIndex;
    public static int LizardCageIndex;
    public static int LizardEggIndex;
    public static int CephadromeCageIndex;
    public static int CephadromeEggIndex;
    public static int DragonCageIndex;
    public static int DragonEggIndex;
    public static int BeeCageIndex;
    public static int HorseCageIndex;
    public static int BeeEggIndex;
    public static int FireflyCageIndex;
    public static int ChipmunkCageIndex;
    public static int GazelleCageIndex;
    public static int OstrichCageIndex;
    public static int TrooperCageIndex;
    public static int SpitCageIndex;
    public static int StinkCageIndex;
    public static int TrooperEggIndex;
    public static int SpitEggIndex;
    public static int StinkEggIndex;
    public static int OstrichEggIndex;
    public static int GazelleEggIndex;
    public static int ChipmunkEggIndex;
    public static int CreepingHorrorCageIndex;
    public static int TerribleTerrorCageIndex;
    public static int CliffRacerCageIndex;
    public static int TriffidCageIndex;
    public static int PitchBlackCageIndex;
    public static int LurkingTerrorCageIndex;
    public static int CreepingHorrorEggIndex;
    public static int TerribleTerrorEggIndex;
    public static int CliffRacerEggIndex;
    public static int TriffidEggIndex;
    public static int PitchBlackEggIndex;
    public static int LurkingTerrorEggIndex;
    public static int GodzillaEggIndex;
    public static int WormSmallCageIndex;
    public static int WormMediumCageIndex;
    public static int WormLargeCageIndex;
    public static int CassowaryCageIndex;
    public static int CloudSharkCageIndex;
    public static int GoldFishCageIndex;
    public static int LeafMonsterCageIndex;
    public static int SmallWormEggIndex;
    public static int MediumWormEggIndex;
    public static int LargeWormEggIndex;
    public static int CassowaryEggIndex;
    public static int CloudSharkEggIndex;
    public static int GoldFishEggIndex;
    public static int LeafMonsterEggIndex;
    public static int TshirtEggIndex;
    public static int EnderKnightCageIndex;
    public static int EnderReaperCageIndex;
    public static int EnderKnightEggIndex;
    public static int EnderReaperEggIndex;
    public static int BeaverCageIndex;
    public static int BeaverEggIndex;
    public static int RotatorEggIndex;
    public static int VortexEggIndex;
    public static int PeacockEggIndex;
    public static int FairyEggIndex;
    public static int DungeonBeastEggIndex;
    public static int RatEggIndex;
    public static int FlounderEggIndex;
    public static int WhaleEggIndex;
    public static int IrukandjiEggIndex;
    public static int SkateEggIndex;
    public static int UrchinEggIndex;
    public static int RotatorCageIndex;
    public static int VortexCageIndex;
    public static int PeacockCageIndex;
    public static int FairyCageIndex;
    public static int DungeonBeastCageIndex;
    public static int RatCageIndex;
    public static int FlounderCageIndex;
    public static int WhaleCageIndex;
    public static int IrukandjiCageIndex;
    public static int SkateCageIndex;
    public static int UrchinCageIndex;
    public static int Robot1EggIndex;
    public static int Robot2EggIndex;
    public static int Robot3EggIndex;
    public static int Robot4EggIndex;
    public static int GhostEggIndex;
    public static int GhostSkellyEggIndex;
    public static int BrownAntEggIndex;
    public static int RedAntEggIndex;
    public static int RainbowAntEggIndex;
    public static int UnstableAntEggIndex;
    public static int TermiteEggIndex;
    public static int ButterflyEggIndex;
    public static int MothEggIndex;
    public static int MosquitoEggIndex;
    public static int FireflyEggIndex;
    public static int TRexEggIndex;
    public static int HerculesEggIndex;
    public static int MantisEggIndex;
    public static int StinkyEggIndex;
    public static int Robot5EggIndex;
    public static int CoinEggIndex;
    public static int TRexCageIndex;
    public static int HerculesCageIndex;
    public static int MantisCageIndex;
    public static int StinkyCageIndex;
    public static int BoyfriendEggIndex;
    public static int TheKingEggIndex;
    public static int ThePrinceEggIndex;
    public static int EasterBunnyEggIndex;
    public static int MolenoidEggIndex;
    public static int SeaMonsterEggIndex;
    public static int SeaViperEggIndex;
    public static int CaterKillerEggIndex;
    public static int LeonCageIndex;
    public static int LeonEggIndex;
    public static int HammerheadCageIndex;
    public static int HammerheadEggIndex;
    public static int RubberDuckyCageIndex;
    public static int RubberDuckyEggIndex;
    public static int CrystalCowEggIndex;
    public static int VillagerCowEggIndex;
    public static int CriminalEggIndex;
    public static int TheQueenEggIndex;
    public static int BrutalflyEggIndex;
    public static int NastysaurusEggIndex;
    public static int PointysaurusEggIndex;
    public static int CricketEggIndex;
    public static int ThePrincessEggIndex;
    public static int FrogEggIndex;
    public static int BrutalflyCageIndex;
    public static int NastysaurusCageIndex;
    public static int PointysaurusCageIndex;
    public static int CricketCageIndex;
    public static int FrogCageIndex;
    public static int JefferyEggIndex;
    public static int AntRobotEggIndex;
    public static int SpiderRobotEggIndex;
    public static int SpiderDriverEggIndex;
    public static int SpiderDriverCageIndex;
    public static int CrabEggIndex;
    public static int CrabCageIndex;
    
    static {
        OreSpawnConstants.OREBLOCK_START_OFFSET = 0;
        OreSpawnConstants.NUMBER_OF_OREBLOCKS = 97;
        OreSpawnConstants.SpiderBlockID = 0;
        OreSpawnConstants.BatBlockID = 1;
        OreSpawnConstants.CowBlockID = 2;
        OreSpawnConstants.PigBlockID = 3;
        OreSpawnConstants.SquidBlockID = 4;
        OreSpawnConstants.ChickenBlockID = 5;
        OreSpawnConstants.CreeperBlockID = 6;
        OreSpawnConstants.SkeletonBlockID = 7;
        OreSpawnConstants.ZombieBlockID = 8;
        OreSpawnConstants.SlimeBlockID = 9;
        OreSpawnConstants.GhastBlockID = 10;
        OreSpawnConstants.ZombiePigmanBlockID = 11;
        OreSpawnConstants.EndermanBlockID = 12;
        OreSpawnConstants.CaveSpiderBlockID = 13;
        OreSpawnConstants.SilverfishBlockID = 14;
        OreSpawnConstants.MagmaCubeBlockID = 15;
        OreSpawnConstants.WitchBlockID = 16;
        OreSpawnConstants.SheepBlockID = 17;
        OreSpawnConstants.WolfBlockID = 18;
        OreSpawnConstants.MooshroomBlockID = 19;
        OreSpawnConstants.OcelotBlockID = 20;
        OreSpawnConstants.BlazeBlockID = 21;
        OreSpawnConstants.WitherSkeletonBlockID = 22;
        OreSpawnConstants.EnderDragonBlockID = 23;
        OreSpawnConstants.SnowGolemBlockID = 24;
        OreSpawnConstants.IronGolemBlockID = 25;
        OreSpawnConstants.WitherBossBlockID = 26;
        OreSpawnConstants.GirlfriendBlockID = 27;
        OreSpawnConstants.RedCowBlockID = 28;
        OreSpawnConstants.GoldCowBlockID = 29;
        OreSpawnConstants.EnchantedCowBlockID = 30;
        OreSpawnConstants.MOTHRABlockID = 31;
        OreSpawnConstants.AloBlockID = 32;
        OreSpawnConstants.CryoBlockID = 33;
        OreSpawnConstants.CamaBlockID = 34;
        OreSpawnConstants.VeloBlockID = 35;
        OreSpawnConstants.HydroBlockID = 36;
        OreSpawnConstants.BasilBlockID = 37;
        OreSpawnConstants.DragonflyBlockID = 38;
        OreSpawnConstants.EmperorScorpionBlockID = 39;
        OreSpawnConstants.ScorpionBlockID = 40;
        OreSpawnConstants.CaveFisherBlockID = 41;
        OreSpawnConstants.SpyroBlockID = 42;
        OreSpawnConstants.BaryonyxBlockID = 43;
        OreSpawnConstants.GammaMetroidBlockID = 44;
        OreSpawnConstants.CockateilBlockID = 45;
        OreSpawnConstants.KyuubiBlockID = 46;
        OreSpawnConstants.AlienBlockID = 47;
        OreSpawnConstants.AttackSquidBlockID = 48;
        OreSpawnConstants.WaterDragonBlockID = 49;
        OreSpawnConstants.KrakenBlockID = 50;
        OreSpawnConstants.LizardBlockID = 51;
        OreSpawnConstants.CephadromeBlockID = 52;
        OreSpawnConstants.DragonBlockID = -1;
        OreSpawnConstants.BeeBlockID = 54;
        OreSpawnConstants.HorseBlockID = 55;
        OreSpawnConstants.TrooperBugBlockID = 56;
        OreSpawnConstants.SpitBugBlockID = 57;
        OreSpawnConstants.StinkBugBlockID = 58;
        OreSpawnConstants.OstrichBlockID = 59;
        OreSpawnConstants.GazelleBlockID = 60;
        OreSpawnConstants.ChipmunkBlockID = 61;
        OreSpawnConstants.CreepingHorrorBlockID = 62;
        OreSpawnConstants.TerribleTerrorBlockID = 63;
        OreSpawnConstants.CliffRacerBlockID = 64;
        OreSpawnConstants.TriffidBlockID = 65;
        OreSpawnConstants.PitchBlackBlockID = 66;
        OreSpawnConstants.LurkingTerrorBlockID = 67;
        OreSpawnConstants.GodzillaPartBlockID = 68;
        OreSpawnConstants.SmallWormBlockID = 69;
        OreSpawnConstants.MediumWormBlockID = 70;
        OreSpawnConstants.LargeWormBlockID = 71;
        OreSpawnConstants.CassowaryBlockID = 72;
        OreSpawnConstants.CloudSharkBlockID = 73;
        OreSpawnConstants.GoldFishBlockID = 74;
        OreSpawnConstants.LeafMonsterBlockID = 75;
        OreSpawnConstants.TshirtBlockID = 76;
        OreSpawnConstants.EnderKnightBlockID = 77;
        OreSpawnConstants.EnderReaperBlockID = 78;
        OreSpawnConstants.BeaverBlockID = 79;
        OreSpawnConstants.TRexBlockID = 80;
        OreSpawnConstants.HerculesBlockID = 81;
        OreSpawnConstants.MantisBlockID = 82;
        OreSpawnConstants.StinkyBlockID = 83;
        OreSpawnConstants.BoyfriendBlockID = 84;
        OreSpawnConstants.TheKingPartBlockID = 85;
        OreSpawnConstants.EasterBunnyBlockID = 86;
        OreSpawnConstants.CaterKillerBlockID = 87;
        OreSpawnConstants.MolenoidBlockID = 88;
        OreSpawnConstants.SeaMonsterBlockID = 89;
        OreSpawnConstants.SeaViperBlockID = 90;
        OreSpawnConstants.LeonBlockID = 91;
        OreSpawnConstants.HammerheadBlockID = 92;
        OreSpawnConstants.RubberDuckyBlockID = 93;
        OreSpawnConstants.VillagerBlockID = 94;
        OreSpawnConstants.CriminalBlockID = 95;
        OreSpawnConstants.TheQueenPartBlockID = 96;
        OreSpawnConstants.OreSaltBlockID = 100;
        OreSpawnConstants.UraniumBlockID = 101;
        OreSpawnConstants.TitaniumBlockID = 102;
        OreSpawnConstants.OreAmethystBlockID = 103;
        OreSpawnConstants.OreRubyBlockID = 104;
        OreSpawnConstants.RTPBlockID = 105;
        OreSpawnConstants.LavafoamBlockID = 106;
        OreSpawnConstants.BlockUraniumBlockID = 107;
        OreSpawnConstants.BlockTitaniumBlockID = 108;
        OreSpawnConstants.BlockRubyBlockID = 109;
        OreSpawnConstants.BlockAmethystBlockID = 110;
        OreSpawnConstants.EnderPearlBlockID = 111;
        OreSpawnConstants.EyeOfEnderBlockID = 112;
        OreSpawnConstants.SkyTreeLogBlockID = 113;
        OreSpawnConstants.DuplicatorLogBlockID = 114;
        OreSpawnConstants.AntBlockID = 115;
        OreSpawnConstants.RedAntBlockID = 116;
        OreSpawnConstants.RainbowAntBlockID = 117;
        OreSpawnConstants.UnstableAntBlockID = 118;
        OreSpawnConstants.GodzillaBlockID = 119;
        OreSpawnConstants.TermiteBlockID = 120;
        OreSpawnConstants.CrystalTermiteBlockID = 121;
        OreSpawnConstants.TheKingBlockID = 122;
        OreSpawnConstants.MoleDirtBlockID = 123;
        OreSpawnConstants.BlockMobzillaScaleBlockID = 124;
        OreSpawnConstants.TheQueenBlockID = 125;
        OreSpawnConstants.AppleLeavesBlockID = 150;
        OreSpawnConstants.ExperienceLeavesBlockID = 151;
        OreSpawnConstants.LeavesScaryID = 152;
        OreSpawnConstants.StrawberryPlantBlockID = 153;
        OreSpawnConstants.FireflyPlantBlockID = 154;
        OreSpawnConstants.ButterflyPlantBlockID = 155;
        OreSpawnConstants.MothPlantBlockID = 156;
        OreSpawnConstants.MosquitoPlantBlockID = 157;
        OreSpawnConstants.ExperiencePlantBlockID = 158;
        OreSpawnConstants.FlowerPinkID = 159;
        OreSpawnConstants.FlowerBlueID = 160;
        OreSpawnConstants.FlowerBlackID = 161;
        OreSpawnConstants.FlowerScaryID = 162;
        OreSpawnConstants.CornPlant1BlockID = 163;
        OreSpawnConstants.CornPlant2BlockID = 164;
        OreSpawnConstants.CornPlant3BlockID = 165;
        OreSpawnConstants.CornPlant4BlockID = 166;
        OreSpawnConstants.TomatoPlant1BlockID = 167;
        OreSpawnConstants.TomatoPlant2BlockID = 168;
        OreSpawnConstants.TomatoPlant3BlockID = 169;
        OreSpawnConstants.TomatoPlant4BlockID = 170;
        OreSpawnConstants.LettucePlant1BlockID = 171;
        OreSpawnConstants.LettucePlant2BlockID = 172;
        OreSpawnConstants.LettucePlant3BlockID = 173;
        OreSpawnConstants.LettucePlant4BlockID = 174;
        OreSpawnConstants.RadishPlantBlockID = 175;
        OreSpawnConstants.LeavesCherryID = 176;
        OreSpawnConstants.LeavesPeachID = 177;
        OreSpawnConstants.RicePlantBlockID = 178;
        OreSpawnConstants.QuinoaPlant1BlockID = 179;
        OreSpawnConstants.QuinoaPlant2BlockID = 180;
        OreSpawnConstants.QuinoaPlant3BlockID = 181;
        OreSpawnConstants.QuinoaPlant4BlockID = 182;
        OreSpawnConstants.KrakenRepellentBlockID = 190;
        OreSpawnConstants.CreeperRepellentBlockID = 191;
        OreSpawnConstants.ExtremeTorchBlockID = 192;
        OreSpawnConstants.IslandBlockID = 193;
        OreSpawnConstants.PizzaBlockID = 194;
        OreSpawnConstants.KingSpawnerBlockID = 195;
        OreSpawnConstants.DungeonSpawnerBlockID = 196;
        OreSpawnConstants.QueenSpawnerBlockID = 197;
        OreSpawnConstants.DuctTapeBlockID = 198;
        OreSpawnConstants.CrystalStoneBlockID = 200;
        OreSpawnConstants.CrystalCoalBlockID = 201;
        OreSpawnConstants.CrystalGrassBlockID = 202;
        OreSpawnConstants.CrystalFlowerRedBlockID = 203;
        OreSpawnConstants.CrystalFlowerGreenBlockID = 204;
        OreSpawnConstants.CrystalFlowerBlueBlockID = 205;
        OreSpawnConstants.CrystalFlowerYellowBlockID = 206;
        OreSpawnConstants.CrystalTreeLogBlockID = 207;
        OreSpawnConstants.CrystalTreeLeavesBlockID = 208;
        OreSpawnConstants.CrystalCrystalBlockID = 209;
        OreSpawnConstants.CrystalPlanksBlockID = 210;
        OreSpawnConstants.CrystalWorkbenchBlockID = 211;
        OreSpawnConstants.CrystalFurnaceBlockID = 212;
        OreSpawnConstants.CrystalFurnaceBlockOnID = 213;
        OreSpawnConstants.CrystalTorchBlockID = 214;
        OreSpawnConstants.CrystalTreeLeaves2BlockID = 215;
        OreSpawnConstants.CrystalPinkBlockBlockID = 216;
        OreSpawnConstants.TigersEyeBlockID = 217;
        OreSpawnConstants.TigersEyeBlockBlockID = 218;
        OreSpawnConstants.CrystalRatBlockID = 219;
        OreSpawnConstants.CrystalFairyBlockID = 220;
        OreSpawnConstants.CrystalTreeLeaves3BlockID = 221;
        OreSpawnConstants.CrystalPlantBlockID = 222;
        OreSpawnConstants.CrystalPlant2BlockID = 223;
        OreSpawnConstants.CrystalPlant3BlockID = 224;
        OreSpawnConstants.RedAntTrollBlockID = 225;
        OreSpawnConstants.TermiteTrollBlockID = 226;
        OreSpawnConstants.CRYSTAL_OREBLOCK_START_OFFSET = 250;
        OreSpawnConstants.CRYSTAL_NUMBER_OF_OREBLOCKS = 12;
        OreSpawnConstants.UrchinBlockID = 250;
        OreSpawnConstants.FlounderBlockID = 251;
        OreSpawnConstants.SkateBlockID = 252;
        OreSpawnConstants.RotatorBlockID = 253;
        OreSpawnConstants.PeacockBlockID = 254;
        OreSpawnConstants.FairyBlockID = 255;
        OreSpawnConstants.DungeonBeastBlockID = 256;
        OreSpawnConstants.VortexBlockID = 257;
        OreSpawnConstants.RatBlockID = 258;
        OreSpawnConstants.WhaleBlockID = 259;
        OreSpawnConstants.IrukandjiBlockID = 260;
        OreSpawnConstants.CrystalCowBlockID = 261;
        OreSpawnConstants.OREBLOCK_START_OFFSET_TWO = 300;
        OreSpawnConstants.NUMBER_OF_OREBLOCKS_TWO = 7;
        OreSpawnConstants.BrutalflyBlockID = 300;
        OreSpawnConstants.NastysaurusBlockID = 301;
        OreSpawnConstants.PointysaurusBlockID = 302;
        OreSpawnConstants.CricketBlockID = 303;
        OreSpawnConstants.FrogBlockID = 304;
        OreSpawnConstants.SpiderDriverBlockID = 305;
        OreSpawnConstants.CrabBlockID = 306;
        OreSpawnConstants.EmptyCageItemID = 0;
        OreSpawnConstants.SpiderCageItemID = 1;
        OreSpawnConstants.BatCageItemID = 2;
        OreSpawnConstants.CowCageItemID = 3;
        OreSpawnConstants.PigCageItemID = 4;
        OreSpawnConstants.SquidCageItemID = 5;
        OreSpawnConstants.ChickenCageItemID = 6;
        OreSpawnConstants.CreeperCageItemID = 7;
        OreSpawnConstants.SkeletonCageItemID = 8;
        OreSpawnConstants.ZombieCageItemID = 9;
        OreSpawnConstants.SlimeCageItemID = 10;
        OreSpawnConstants.GhastCageItemID = 11;
        OreSpawnConstants.ZombiePigmanCageItemID = 12;
        OreSpawnConstants.EndermanCageItemID = 13;
        OreSpawnConstants.CaveSpiderCageItemID = 14;
        OreSpawnConstants.SilverfishCageItemID = 15;
        OreSpawnConstants.MagmaCubeCageItemID = 16;
        OreSpawnConstants.WitchCageItemID = 17;
        OreSpawnConstants.SheepCageItemID = 18;
        OreSpawnConstants.WolfCageItemID = 19;
        OreSpawnConstants.MooshroomCageItemID = 20;
        OreSpawnConstants.OcelotCageItemID = 21;
        OreSpawnConstants.BlazeCageItemID = 22;
        OreSpawnConstants.GirlfriendCageItemID = 23;
        OreSpawnConstants.WitherSkeletonCageItemID = 24;
        OreSpawnConstants.EnderDragonCageItemID = 25;
        OreSpawnConstants.SnowGolemCageItemID = 26;
        OreSpawnConstants.IronGolemCageItemID = 27;
        OreSpawnConstants.WitherBossCageItemID = 28;
        OreSpawnConstants.RedCowCageItemID = 29;
        OreSpawnConstants.GoldCowCageItemID = 30;
        OreSpawnConstants.EnchantedCowCageItemID = 31;
        OreSpawnConstants.MOTHRACageItemID = 32;
        OreSpawnConstants.AloCageItemID = 33;
        OreSpawnConstants.CryoCageItemID = 34;
        OreSpawnConstants.CamaCageItemID = 35;
        OreSpawnConstants.VeloCageItemID = 36;
        OreSpawnConstants.HydroCageItemID = 37;
        OreSpawnConstants.BasilCageItemID = 38;
        OreSpawnConstants.DragonflyCageItemID = 39;
        OreSpawnConstants.ScorpionCageItemID = 40;
        OreSpawnConstants.EmperorScorpionCageItemID = 41;
        OreSpawnConstants.SpyroCageItemID = 42;
        OreSpawnConstants.BaryonyxCageItemID = 43;
        OreSpawnConstants.GammaMetroidCageItemID = 44;
        OreSpawnConstants.CaveFisherCageItemID = 45;
        OreSpawnConstants.CockateilCageItemID = 46;
        OreSpawnConstants.KyuubiCageItemID = 47;
        OreSpawnConstants.AlienCageItemID = 48;
        OreSpawnConstants.AttackSquidCageItemID = 49;
        OreSpawnConstants.WaterDragonCageItemID = 50;
        OreSpawnConstants.KrakenCageItemID = 51;
        OreSpawnConstants.LizardCageItemID = 52;
        OreSpawnConstants.CephadromeCageItemID = 53;
        OreSpawnConstants.DragonCageItemID = 54;
        OreSpawnConstants.BeeCageItemID = 55;
        OreSpawnConstants.HorseCageItemID = 56;
        OreSpawnConstants.FireflyCageItemID = 57;
        OreSpawnConstants.ChipmunkCageItemID = 58;
        OreSpawnConstants.GazelleCageItemID = 59;
        OreSpawnConstants.OstrichCageItemID = 60;
        OreSpawnConstants.TrooperCageItemID = 61;
        OreSpawnConstants.SpitCageItemID = 62;
        OreSpawnConstants.StinkCageItemID = 63;
        OreSpawnConstants.CreepingHorrorCageItemID = 64;
        OreSpawnConstants.TerribleTerrorCageItemID = 65;
        OreSpawnConstants.CliffRacerCageItemID = 66;
        OreSpawnConstants.TriffidCageItemID = 67;
        OreSpawnConstants.PitchBlackCageItemID = 68;
        OreSpawnConstants.LurkingTerrorCageItemID = 69;
        OreSpawnConstants.WormSmallCageItemID = 70;
        OreSpawnConstants.WormMediumCageItemID = 71;
        OreSpawnConstants.WormLargeCageItemID = 72;
        OreSpawnConstants.CassowaryCageItemID = 73;
        OreSpawnConstants.CloudSharkCageItemID = 74;
        OreSpawnConstants.GoldFishCageItemID = 75;
        OreSpawnConstants.LeafMonsterCageItemID = 76;
        OreSpawnConstants.EnderKnightCageItemID = 77;
        OreSpawnConstants.EnderReaperCageItemID = 78;
        OreSpawnConstants.BeaverCageItemID = 79;
        OreSpawnConstants.UrchinCageItemID = 80;
        OreSpawnConstants.FlounderCageItemID = 81;
        OreSpawnConstants.SkateCageItemID = 82;
        OreSpawnConstants.RotatorCageItemID = 83;
        OreSpawnConstants.PeacockCageItemID = 84;
        OreSpawnConstants.FairyCageItemID = 85;
        OreSpawnConstants.DungeonBeastCageItemID = 86;
        OreSpawnConstants.VortexCageItemID = 87;
        OreSpawnConstants.RatCageItemID = 88;
        OreSpawnConstants.WhaleCageItemID = 89;
        OreSpawnConstants.IrukandjiCageItemID = 90;
        OreSpawnConstants.TRexCageItemID = 91;
        OreSpawnConstants.HerculesCageItemID = 92;
        OreSpawnConstants.MantisCageItemID = 93;
        OreSpawnConstants.StinkyCageItemID = 94;
        OreSpawnConstants.BoyfriendCageItemID = 95;
        OreSpawnConstants.EasterBunnyCageItemID = 96;
        OreSpawnConstants.CaterKillerCageItemID = 97;
        OreSpawnConstants.MolenoidCageItemID = 98;
        OreSpawnConstants.SeaMonsterCageItemID = 99;
        OreSpawnConstants.WitherSkeletonEggItemID = 100;
        OreSpawnConstants.EnderDragonEggItemID = 101;
        OreSpawnConstants.SnowGolemEggItemID = 102;
        OreSpawnConstants.IronGolemEggItemID = 103;
        OreSpawnConstants.WitherBossEggItemID = 104;
        OreSpawnConstants.GirlfriendEggItemID = 105;
        OreSpawnConstants.RedCowEggItemID = 106;
        OreSpawnConstants.GoldCowEggItemID = 107;
        OreSpawnConstants.EnchantedCowEggItemID = 108;
        OreSpawnConstants.MOTHRAEggItemID = 109;
        OreSpawnConstants.AloEggItemID = 110;
        OreSpawnConstants.CryoEggItemID = 111;
        OreSpawnConstants.CamaEggItemID = 112;
        OreSpawnConstants.VeloEggItemID = 113;
        OreSpawnConstants.HydroEggItemID = 114;
        OreSpawnConstants.BasilEggItemID = 115;
        OreSpawnConstants.DragonflyEggItemID = 116;
        OreSpawnConstants.EmperorScorpionEggItemID = 117;
        OreSpawnConstants.ScorpionEggItemID = 118;
        OreSpawnConstants.CaveFisherEggItemID = 119;
        OreSpawnConstants.SpyroEggItemID = 120;
        OreSpawnConstants.BaryonyxEggItemID = 121;
        OreSpawnConstants.GammaMetroidEggItemID = 122;
        OreSpawnConstants.CockateilEggItemID = 123;
        OreSpawnConstants.KyuubiEggItemID = 124;
        OreSpawnConstants.AlienEggItemID = 125;
        OreSpawnConstants.AttackSquidEggItemID = 126;
        OreSpawnConstants.WaterDragonEggItemID = 127;
        OreSpawnConstants.KrakenEggItemID = 128;
        OreSpawnConstants.LizardEggItemID = 129;
        OreSpawnConstants.CephadromeEggItemID = 130;
        OreSpawnConstants.DragonEggItemID = 131;
        OreSpawnConstants.BeeEggItemID = 132;
        OreSpawnConstants.TrooperEggItemID = 133;
        OreSpawnConstants.SpitEggItemID = 134;
        OreSpawnConstants.StinkEggItemID = 135;
        OreSpawnConstants.OstrichEggItemID = 136;
        OreSpawnConstants.GazelleEggItemID = 137;
        OreSpawnConstants.ChipmunkEggItemID = 138;
        OreSpawnConstants.CreepingHorrorEggItemID = 139;
        OreSpawnConstants.TerribleTerrorEggItemID = 140;
        OreSpawnConstants.CliffRacerEggItemID = 141;
        OreSpawnConstants.TriffidEggItemID = 142;
        OreSpawnConstants.PitchBlackEggItemID = 143;
        OreSpawnConstants.LurkingTerrorEggItemID = 144;
        OreSpawnConstants.GodzillaEggItemID = 145;
        OreSpawnConstants.SmallWormEggItemID = 146;
        OreSpawnConstants.MediumWormEggItemID = 147;
        OreSpawnConstants.LargeWormEggItemID = 148;
        OreSpawnConstants.CassowaryEggItemID = 149;
        OreSpawnConstants.UraniumNuggetItemID = 150;
        OreSpawnConstants.TitaniumNuggetItemID = 151;
        OreSpawnConstants.UraniumIngotItemID = 152;
        OreSpawnConstants.TitaniumIngotItemID = 153;
        OreSpawnConstants.GreenGooItemID = 154;
        OreSpawnConstants.DeadStinkBugItemID = 155;
        OreSpawnConstants.MothScaleItemID = 156;
        OreSpawnConstants.LavaEelItemID = 157;
        OreSpawnConstants.NightmareScaleItemID = 158;
        OreSpawnConstants.EmperorScorpionScaleItemID = 159;
        OreSpawnConstants.BasiliskScaleItemID = 160;
        OreSpawnConstants.WaterDragonScaleItemID = 161;
        OreSpawnConstants.JumpyBugScaleItemID = 162;
        OreSpawnConstants.KrakenToothItemID = 163;
        OreSpawnConstants.GodzillaScaleItemID = 164;
        OreSpawnConstants.CloudSharkEggItemID = 165;
        OreSpawnConstants.GoldFishEggItemID = 166;
        OreSpawnConstants.LeafMonsterEggItemID = 167;
        OreSpawnConstants.TshirtEggItemID = 168;
        OreSpawnConstants.EnderKnightEggItemID = 169;
        OreSpawnConstants.EnderReaperEggItemID = 170;
        OreSpawnConstants.BeaverEggItemID = 171;
        OreSpawnConstants.Robot5EggItemID = 172;
        OreSpawnConstants.CoinEggItemID = 173;
        OreSpawnConstants.SeaViperCageItemID = 174;
        OreSpawnConstants.FireFishItemID = 175;
        OreSpawnConstants.SunFishItemID = 176;
        OreSpawnConstants.SparkFishItemID = 177;
        OreSpawnConstants.SaltItemID = 178;
        OreSpawnConstants.PopcornItemID = 179;
        OreSpawnConstants.ButteredPopcornItemID = 180;
        OreSpawnConstants.ButteredSaltedPopcornItemID = 181;
        OreSpawnConstants.PopcornBagItemID = 182;
        OreSpawnConstants.ButterItemID = 183;
        OreSpawnConstants.StrawberryItemID = 184;
        OreSpawnConstants.CornCobItemID = 185;
        OreSpawnConstants.CornDogItemID = 186;
        OreSpawnConstants.RawCornDogItemID = 187;
        OreSpawnConstants.ButterCandyItemID = 188;
        OreSpawnConstants.BaconItemID = 189;
        OreSpawnConstants.RawBaconItemID = 190;
        OreSpawnConstants.GreenFishItemID = 191;
        OreSpawnConstants.BlueFishItemID = 192;
        OreSpawnConstants.PinkFishItemID = 193;
        OreSpawnConstants.RockFishItemID = 194;
        OreSpawnConstants.WoodFishItemID = 195;
        OreSpawnConstants.GreyFishItemID = 196;
        OreSpawnConstants.TomatoItemID = 197;
        OreSpawnConstants.LettuceItemID = 198;
        OreSpawnConstants.RadishItemID = 199;
        OreSpawnConstants.SaladItemID = 200;
        OreSpawnConstants.BLTItemID = 201;
        OreSpawnConstants.CherryItemID = 202;
        OreSpawnConstants.PeachItemID = 203;
        OreSpawnConstants.PizzaItemID = 204;
        OreSpawnConstants.CheeseItemID = 205;
        OreSpawnConstants.RawPeacockItemID = 206;
        OreSpawnConstants.PeacockItemID = 207;
        OreSpawnConstants.CrystalAppleItemID = 208;
        OreSpawnConstants.RiceItemID = 209;
        OreSpawnConstants.StrawberrySeedItemID = 210;
        OreSpawnConstants.AppleSeedItemID = 211;
        OreSpawnConstants.ButterflySeedItemID = 212;
        OreSpawnConstants.MothSeedItemID = 213;
        OreSpawnConstants.MosquitoSeedItemID = 214;
        OreSpawnConstants.FireflySeedItemID = 215;
        OreSpawnConstants.ExperienceTreeSeedItemID = 216;
        OreSpawnConstants.CherrySeedItemID = 217;
        OreSpawnConstants.PeachSeedItemID = 218;
        OreSpawnConstants.RotatorEggItemID = 219;
        OreSpawnConstants.PeacockEggItemID = 220;
        OreSpawnConstants.FairyEggItemID = 221;
        OreSpawnConstants.DungeonBeastEggItemID = 222;
        OreSpawnConstants.VortexEggItemID = 223;
        OreSpawnConstants.QuinoaItemID = 224;
        OreSpawnConstants.TRexEggItemID = 225;
        OreSpawnConstants.HerculesEggItemID = 226;
        OreSpawnConstants.MantisEggItemID = 227;
        OreSpawnConstants.StinkyEggItemID = 228;
        OreSpawnConstants.ZooKeeperItemID = 230;
        OreSpawnConstants.StepUpItemID = 232;
        OreSpawnConstants.StepDownItemID = 233;
        OreSpawnConstants.StepAccrossItemID = 234;
        OreSpawnConstants.ElevatorItemID = 235;
        OreSpawnConstants.MagicAppleItemID = 236;
        OreSpawnConstants.MinersDreamItemID = 237;
        OreSpawnConstants.ExperienceCatcherItemID = 238;
        OreSpawnConstants.IceBallItemID = 239;
        OreSpawnConstants.ThunderStaffItemID = 240;
        OreSpawnConstants.PoisonSwordItemID = 241;
        OreSpawnConstants.LaserBallItemID = 242;
        OreSpawnConstants.RayGunItemID = 243;
        OreSpawnConstants.WaterBallItemID = 244;
        OreSpawnConstants.UltimateArrowItemID = 245;
        OreSpawnConstants.SunspotUrchinItemID = 246;
        OreSpawnConstants.AcidItemID = 247;
        OreSpawnConstants.RedHeelsItemID = 248;
        OreSpawnConstants.BlackHeelsItemID = 249;
        OreSpawnConstants.SlippersItemID = 250;
        OreSpawnConstants.BootsItemID = 251;
        OreSpawnConstants.CreeperLauncherItemID = 252;
        OreSpawnConstants.NetherLostItemID = 253;
        OreSpawnConstants.CrystalSticksItemID = 254;
        OreSpawnConstants.PeacockFeatherItemID = 255;
        OreSpawnConstants.RatSwordItemID = 256;
        OreSpawnConstants.FairySwordItemID = 257;
        OreSpawnConstants.IrukandjiItemID = 258;
        OreSpawnConstants.GameControllerItemID = 259;
        OreSpawnConstants.AmethystItemID = 260;
        OreSpawnConstants.AmethystSwordItemID = 261;
        OreSpawnConstants.AmethystPickaxeItemID = 262;
        OreSpawnConstants.AmethystShovelItemID = 263;
        OreSpawnConstants.AmethystHoeItemID = 264;
        OreSpawnConstants.AmethystAxeItemID = 265;
        OreSpawnConstants.AmethystHelmetItemID = 266;
        OreSpawnConstants.AmethystBodyItemID = 267;
        OreSpawnConstants.AmethystLegsItemID = 268;
        OreSpawnConstants.AmethystBootsItemID = 269;
        OreSpawnConstants.RubyItemID = 270;
        OreSpawnConstants.RubySwordItemID = 271;
        OreSpawnConstants.RubyPickaxeItemID = 272;
        OreSpawnConstants.RubyShovelItemID = 273;
        OreSpawnConstants.RubyHoeItemID = 274;
        OreSpawnConstants.RubyAxeItemID = 275;
        OreSpawnConstants.RubyHelmetItemID = 276;
        OreSpawnConstants.RubyBodyItemID = 277;
        OreSpawnConstants.RubyLegsItemID = 278;
        OreSpawnConstants.RubyBootsItemID = 279;
        OreSpawnConstants.EmeraldSwordItemID = 280;
        OreSpawnConstants.EmeraldPickaxeItemID = 281;
        OreSpawnConstants.EmeraldShovelItemID = 282;
        OreSpawnConstants.EmeraldHoeItemID = 283;
        OreSpawnConstants.EmeraldAxeItemID = 284;
        OreSpawnConstants.EmeraldHelmetItemID = 285;
        OreSpawnConstants.EmeraldBodyItemID = 286;
        OreSpawnConstants.EmeraldLegsItemID = 287;
        OreSpawnConstants.EmeraldBootsItemID = 288;
        OreSpawnConstants.ExperienceSwordItemID = 289;
        OreSpawnConstants.ExperienceHelmetItemID = 290;
        OreSpawnConstants.ExperienceBodyItemID = 291;
        OreSpawnConstants.ExperienceLegsItemID = 292;
        OreSpawnConstants.ExperienceBootsItemID = 293;
        OreSpawnConstants.MothScaleHelmetItemID = 294;
        OreSpawnConstants.MothScaleBodyItemID = 295;
        OreSpawnConstants.MothScaleLegsItemID = 296;
        OreSpawnConstants.MothScaleBootsItemID = 297;
        OreSpawnConstants.LavaEelHelmetItemID = 298;
        OreSpawnConstants.LavaEelBodyItemID = 299;
        OreSpawnConstants.LavaEelLegsItemID = 300;
        OreSpawnConstants.LavaEelBootsItemID = 301;
        OreSpawnConstants.UltimateSwordItemID = 302;
        OreSpawnConstants.UltimateBowItemID = 303;
        OreSpawnConstants.UltimateFishingRodItemID = 304;
        OreSpawnConstants.UltimatePickaxeItemID = 305;
        OreSpawnConstants.UltimateShovelItemID = 306;
        OreSpawnConstants.UltimateHoeItemID = 307;
        OreSpawnConstants.UltimateAxeItemID = 308;
        OreSpawnConstants.UltimateHelmetItemID = 309;
        OreSpawnConstants.UltimateBodyItemID = 310;
        OreSpawnConstants.UltimateLegsItemID = 311;
        OreSpawnConstants.UltimateBootsItemID = 312;
        OreSpawnConstants.BerthaItemID = 313;
        OreSpawnConstants.SliceItemID = 314;
        OreSpawnConstants.MantisClawItemID = 315;
        OreSpawnConstants.BigHammerItemID = 316;
        OreSpawnConstants.SquidZookaItemID = 317;
        OreSpawnConstants.RoyalItemID = 318;
        OreSpawnConstants.HammyItemID = 319;
        OreSpawnConstants.ZooCage2ItemID = 320;
        OreSpawnConstants.ZooCage4ItemID = 321;
        OreSpawnConstants.ZooCage6ItemID = 322;
        OreSpawnConstants.ZooCage8ItemID = 323;
        OreSpawnConstants.ZooCage10ItemID = 324;
        OreSpawnConstants.SifterItemID = 325;
        OreSpawnConstants.NightmareSwordItemID = 326;
        OreSpawnConstants.InstantShelterItemID = 327;
        OreSpawnConstants.InstantGardenItemID = 328;
        OreSpawnConstants.CrystalWoodSwordItemID = 329;
        OreSpawnConstants.CrystalWoodPickaxeItemID = 330;
        OreSpawnConstants.CrystalWoodShovelItemID = 331;
        OreSpawnConstants.CrystalWoodHoeItemID = 332;
        OreSpawnConstants.CrystalWoodAxeItemID = 333;
        OreSpawnConstants.CrystalPinkSwordItemID = 334;
        OreSpawnConstants.CrystalPinkPickaxeItemID = 335;
        OreSpawnConstants.CrystalPinkShovelItemID = 336;
        OreSpawnConstants.CrystalPinkHoeItemID = 337;
        OreSpawnConstants.CrystalPinkAxeItemID = 338;
        OreSpawnConstants.CrystalStoneSwordItemID = 339;
        OreSpawnConstants.CrystalStonePickaxeItemID = 340;
        OreSpawnConstants.CrystalStoneShovelItemID = 341;
        OreSpawnConstants.CrystalStoneHoeItemID = 342;
        OreSpawnConstants.CrystalStoneAxeItemID = 343;
        OreSpawnConstants.CrystalPinkHelmetItemID = 344;
        OreSpawnConstants.CrystalPinkBodyItemID = 345;
        OreSpawnConstants.CrystalPinkLegsItemID = 346;
        OreSpawnConstants.CrystalPinkBootsItemID = 347;
        OreSpawnConstants.CrystalPinkIngotItemID = 348;
        OreSpawnConstants.TigersEyeSwordItemID = 349;
        OreSpawnConstants.TigersEyePickaxeItemID = 350;
        OreSpawnConstants.TigersEyeShovelItemID = 351;
        OreSpawnConstants.TigersEyeHoeItemID = 352;
        OreSpawnConstants.TigersEyeAxeItemID = 353;
        OreSpawnConstants.TigersEyeHelmetItemID = 354;
        OreSpawnConstants.TigersEyeBodyItemID = 355;
        OreSpawnConstants.TigersEyeLegsItemID = 356;
        OreSpawnConstants.TigersEyeBootsItemID = 357;
        OreSpawnConstants.TigersEyeIngotItemID = 358;
        OreSpawnConstants.PeacockFeatherHelmetItemID = 359;
        OreSpawnConstants.PeacockFeatherBodyItemID = 360;
        OreSpawnConstants.PeacockFeatherLegsItemID = 370;
        OreSpawnConstants.PeacockFeatherBootsItemID = 371;
        OreSpawnConstants.IrukandjiArrowItemID = 372;
        OreSpawnConstants.SkateBowItemID = 373;
        OreSpawnConstants.RatEggItemID = 374;
        OreSpawnConstants.FlounderEggItemID = 375;
        OreSpawnConstants.WhaleEggItemID = 376;
        OreSpawnConstants.IrukandjiEggItemID = 377;
        OreSpawnConstants.SkateEggItemID = 378;
        OreSpawnConstants.UrchinEggItemID = 379;
        OreSpawnConstants.Robot1EggItemID = 380;
        OreSpawnConstants.Robot2EggItemID = 381;
        OreSpawnConstants.Robot3EggItemID = 382;
        OreSpawnConstants.Robot4EggItemID = 383;
        OreSpawnConstants.GhostEggItemID = 384;
        OreSpawnConstants.GhostSkellyEggItemID = 385;
        OreSpawnConstants.BrownAntEggItemID = 386;
        OreSpawnConstants.RedAntEggItemID = 387;
        OreSpawnConstants.RainbowAntEggItemID = 388;
        OreSpawnConstants.UnstableAntEggItemID = 389;
        OreSpawnConstants.TermiteEggItemID = 390;
        OreSpawnConstants.ButterflyEggItemID = 391;
        OreSpawnConstants.MothEggItemID = 392;
        OreSpawnConstants.MosquitoEggItemID = 393;
        OreSpawnConstants.FireflyEggItemID = 394;
        OreSpawnConstants.MobzillaHelmetItemID = 395;
        OreSpawnConstants.MobzillaBodyItemID = 396;
        OreSpawnConstants.MobzillaLegsItemID = 397;
        OreSpawnConstants.MobzillaBootsItemID = 398;
        OreSpawnConstants.BoyfriendEggItemID = 399;
        OreSpawnConstants.TheKingEggItemID = 400;
        OreSpawnConstants.ThePrinceEggItemID = 401;
        OreSpawnConstants.RoyalHelmetItemID = 402;
        OreSpawnConstants.RoyalBodyItemID = 403;
        OreSpawnConstants.RoyalLegsItemID = 404;
        OreSpawnConstants.RoyalBootsItemID = 405;
        OreSpawnConstants.BerthaHandleItemID = 406;
        OreSpawnConstants.BerthaGuardItemID = 407;
        OreSpawnConstants.BerthaBladeItemID = 408;
        OreSpawnConstants.MolenoidNoseItemID = 409;
        OreSpawnConstants.SeaMonsterScaleItemID = 410;
        OreSpawnConstants.WormToothItemID = 411;
        OreSpawnConstants.TRexToothItemID = 412;
        OreSpawnConstants.CaterKillerJawItemID = 413;
        OreSpawnConstants.SeaViperTongueItemID = 414;
        OreSpawnConstants.VortexEyeItemID = 415;
        OreSpawnConstants.EasterBunnyEggItemID = 416;
        OreSpawnConstants.MolenoidEggItemID = 417;
        OreSpawnConstants.SeaMonsterEggItemID = 418;
        OreSpawnConstants.SeaViperEggItemID = 419;
        OreSpawnConstants.CaterKillerEggItemID = 420;
        OreSpawnConstants.RandomDungeonItemID = 421;
        OreSpawnConstants.BattleAxeItemID = 422;
        OreSpawnConstants.LeonCageItemID = 423;
        OreSpawnConstants.LeonEggItemID = 424;
        OreSpawnConstants.HammerheadCageItemID = 425;
        OreSpawnConstants.HammerheadEggItemID = 426;
        OreSpawnConstants.RubberDuckyCageItemID = 427;
        OreSpawnConstants.RubberDuckyEggItemID = 428;
        OreSpawnConstants.CrystalCowCageItemID = 429;
        OreSpawnConstants.VillagerCageItemID = 430;
        OreSpawnConstants.CrystalCowEggItemID = 431;
        OreSpawnConstants.VillagerEggItemID = 432;
        OreSpawnConstants.CriminalCageItemID = 433;
        OreSpawnConstants.CriminalEggItemID = 434;
        OreSpawnConstants.RockItemID = 435;
        OreSpawnConstants.RockSmallItemID = 436;
        OreSpawnConstants.RockRedItemID = 437;
        OreSpawnConstants.RockGreenItemID = 438;
        OreSpawnConstants.RockBlueItemID = 439;
        OreSpawnConstants.RockPurpleItemID = 440;
        OreSpawnConstants.RockSpikeyItemID = 441;
        OreSpawnConstants.RockTNTItemID = 442;
        OreSpawnConstants.RockCrystalRedItemID = 443;
        OreSpawnConstants.RockCrystalGreenItemID = 444;
        OreSpawnConstants.RockCrystalBlueItemID = 445;
        OreSpawnConstants.RockCrystalTNTItemID = 446;
        OreSpawnConstants.ChainsawItemID = 447;
        OreSpawnConstants.TheQueenEggItemID = 448;
        OreSpawnConstants.LapisHelmetItemID = 449;
        OreSpawnConstants.LapisBodyItemID = 450;
        OreSpawnConstants.LapisLegsItemID = 451;
        OreSpawnConstants.LapisBootsItemID = 452;
        OreSpawnConstants.QueenScaleItemID = 453;
        OreSpawnConstants.QueenHelmetItemID = 454;
        OreSpawnConstants.QueenBodyItemID = 455;
        OreSpawnConstants.QueenLegsItemID = 456;
        OreSpawnConstants.QueenBootsItemID = 457;
        OreSpawnConstants.DuctTapeItemID = 458;
        OreSpawnConstants.BrutalflyEggItemID = 459;
        OreSpawnConstants.NastysaurusEggItemID = 460;
        OreSpawnConstants.PointysaurusEggItemID = 461;
        OreSpawnConstants.CricketEggItemID = 462;
        OreSpawnConstants.ThePrincessEggItemID = 463;
        OreSpawnConstants.FrogEggItemID = 464;
        OreSpawnConstants.BrutalflyCageItemID = 465;
        OreSpawnConstants.NastysaurusCageItemID = 466;
        OreSpawnConstants.PointysaurusCageItemID = 467;
        OreSpawnConstants.CricketCageItemID = 468;
        OreSpawnConstants.FrogCageItemID = 469;
        OreSpawnConstants.QueenBattleAxeItemID = 470;
        OreSpawnConstants.SpiderRobotKitItemID = 471;
        OreSpawnConstants.WrenchItemID = 472;
        OreSpawnConstants.AntRobotKitItemID = 473;
        OreSpawnConstants.JefferyEggItemID = 474;
        OreSpawnConstants.AntRobotEggItemID = 475;
        OreSpawnConstants.SpiderRobotEggItemID = 476;
        OreSpawnConstants.SpiderDriverEggItemID = 477;
        OreSpawnConstants.SpiderDriverCageItemID = 478;
        OreSpawnConstants.RawCrabMeatItemID = 479;
        OreSpawnConstants.CrabMeatItemID = 480;
        OreSpawnConstants.CrabbyPattyItemID = 481;
        OreSpawnConstants.CrabEggItemID = 482;
        OreSpawnConstants.CrabCageItemID = 483;
        OreSpawnConstants.RoseSwordItemID = 484;
        OreSpawnConstants.LoveItemID = 485;
        OreSpawnConstants.SHOE_START_INDEX = 2;
        OreSpawnConstants.NUMBER_OF_SHOES = 4;
        OreSpawnConstants.RedHeelsIndex = 2;
        OreSpawnConstants.BlackHeelsIndex = 3;
        OreSpawnConstants.SlippersIndex = 4;
        OreSpawnConstants.BootsIndex = 5;
        OreSpawnConstants.GameControllerIndex = 6;
        OreSpawnConstants.WaterBallIndex = 49;
        OreSpawnConstants.SunspotUrchinIndex = 50;
        OreSpawnConstants.InkSackIndex = 65;
        OreSpawnConstants.LaserBallIndex = 81;
        OreSpawnConstants.IceBallIndex = 84;
        OreSpawnConstants.AcidIndex = 85;
        OreSpawnConstants.IrukandjiIndex = 86;
        OreSpawnConstants.EasterBunnyCageIndex = 150;
        OreSpawnConstants.CaterKillerCageIndex = 151;
        OreSpawnConstants.MolenoidCageIndex = 152;
        OreSpawnConstants.SeaMonsterCageIndex = 153;
        OreSpawnConstants.SeaViperCageIndex = 154;
        OreSpawnConstants.EmptyCageIndex = 160;
        OreSpawnConstants.SpiderCageIndex = 161;
        OreSpawnConstants.BatCageIndex = 162;
        OreSpawnConstants.CowCageIndex = 163;
        OreSpawnConstants.PigCageIndex = 164;
        OreSpawnConstants.SquidCageIndex = 165;
        OreSpawnConstants.ChickenCageIndex = 166;
        OreSpawnConstants.CreeperCageIndex = 167;
        OreSpawnConstants.SkeletonCageIndex = 168;
        OreSpawnConstants.ZombieCageIndex = 169;
        OreSpawnConstants.SlimeCageIndex = 170;
        OreSpawnConstants.GhastCageIndex = 171;
        OreSpawnConstants.ZombiePigmanCageIndex = 172;
        OreSpawnConstants.EndermanCageIndex = 173;
        OreSpawnConstants.CaveSpiderCageIndex = 174;
        OreSpawnConstants.SilverfishCageIndex = 175;
        OreSpawnConstants.MagmaCubeCageIndex = 176;
        OreSpawnConstants.WitchCageIndex = 177;
        OreSpawnConstants.SheepCageIndex = 178;
        OreSpawnConstants.WolfCageIndex = 179;
        OreSpawnConstants.MooshroomCageIndex = 180;
        OreSpawnConstants.OcelotCageIndex = 181;
        OreSpawnConstants.BlazeCageIndex = 182;
        OreSpawnConstants.GirlfriendCageIndex = 183;
        OreSpawnConstants.EnderDragonCageIndex = 184;
        OreSpawnConstants.SnowGolemCageIndex = 185;
        OreSpawnConstants.IronGolemCageIndex = 186;
        OreSpawnConstants.WitherBossCageIndex = 187;
        OreSpawnConstants.WitherSkeletonCageIndex = 188;
        OreSpawnConstants.RedCowCageIndex = 189;
        OreSpawnConstants.GoldCowCageIndex = 190;
        OreSpawnConstants.EnchantedCowCageIndex = 191;
        OreSpawnConstants.MOTHRACageIndex = 208;
        OreSpawnConstants.AloCageIndex = 209;
        OreSpawnConstants.CryoCageIndex = 210;
        OreSpawnConstants.CamaCageIndex = 211;
        OreSpawnConstants.VeloCageIndex = 212;
        OreSpawnConstants.HydroCageIndex = 213;
        OreSpawnConstants.BasilCageIndex = 214;
        OreSpawnConstants.BoyfriendCageIndex = 215;
        OreSpawnConstants.CrystalCowCageIndex = 216;
        OreSpawnConstants.VillagerCageIndex = 217;
        OreSpawnConstants.CriminalCageIndex = 218;
        OreSpawnConstants.WitherSkeletonEggIndex = 192;
        OreSpawnConstants.EnderDragonEggIndex = 193;
        OreSpawnConstants.SnowGolemEggIndex = 194;
        OreSpawnConstants.IronGolemEggIndex = 195;
        OreSpawnConstants.WitherBossEggIndex = 196;
        OreSpawnConstants.GirlfriendEggIndex = 197;
        OreSpawnConstants.RedCowEggIndex = 198;
        OreSpawnConstants.GoldCowEggIndex = 199;
        OreSpawnConstants.EnchantedCowEggIndex = 200;
        OreSpawnConstants.MOTHRAEggIndex = 201;
        OreSpawnConstants.AloEggIndex = 202;
        OreSpawnConstants.CryoEggIndex = 203;
        OreSpawnConstants.CamaEggIndex = 204;
        OreSpawnConstants.VeloEggIndex = 205;
        OreSpawnConstants.HydroEggIndex = 206;
        OreSpawnConstants.BasilEggIndex = 207;
        OreSpawnConstants.DragonflyCageIndex = 220;
        OreSpawnConstants.DragonflyEggIndex = 221;
        OreSpawnConstants.EmperorScorpionCageIndex = 222;
        OreSpawnConstants.EmperorScorpionEggIndex = 223;
        OreSpawnConstants.ScorpionCageIndex = 224;
        OreSpawnConstants.ScorpionEggIndex = 225;
        OreSpawnConstants.CaveFisherCageIndex = 226;
        OreSpawnConstants.CaveFisherEggIndex = 227;
        OreSpawnConstants.SpyroCageIndex = 228;
        OreSpawnConstants.SpyroEggIndex = 229;
        OreSpawnConstants.BaryonyxCageIndex = 230;
        OreSpawnConstants.BaryonyxEggIndex = 231;
        OreSpawnConstants.GammaMetroidCageIndex = 232;
        OreSpawnConstants.GammaMetroidEggIndex = 233;
        OreSpawnConstants.CockateilCageIndex = 234;
        OreSpawnConstants.CockateilEggIndex = 235;
        OreSpawnConstants.KyuubiCageIndex = 236;
        OreSpawnConstants.KyuubiEggIndex = 237;
        OreSpawnConstants.AlienCageIndex = 238;
        OreSpawnConstants.AlienEggIndex = 239;
        OreSpawnConstants.AttackSquidCageIndex = 240;
        OreSpawnConstants.AttackSquidEggIndex = 241;
        OreSpawnConstants.WaterDragonCageIndex = 242;
        OreSpawnConstants.WaterDragonEggIndex = 243;
        OreSpawnConstants.KrakenCageIndex = 244;
        OreSpawnConstants.KrakenEggIndex = 245;
        OreSpawnConstants.LizardCageIndex = 246;
        OreSpawnConstants.LizardEggIndex = 247;
        OreSpawnConstants.CephadromeCageIndex = 248;
        OreSpawnConstants.CephadromeEggIndex = 249;
        OreSpawnConstants.DragonCageIndex = 250;
        OreSpawnConstants.DragonEggIndex = 251;
        OreSpawnConstants.BeeCageIndex = 252;
        OreSpawnConstants.HorseCageIndex = 253;
        OreSpawnConstants.BeeEggIndex = 254;
        OreSpawnConstants.FireflyCageIndex = 255;
        OreSpawnConstants.ChipmunkCageIndex = 256;
        OreSpawnConstants.GazelleCageIndex = 257;
        OreSpawnConstants.OstrichCageIndex = 258;
        OreSpawnConstants.TrooperCageIndex = 259;
        OreSpawnConstants.SpitCageIndex = 260;
        OreSpawnConstants.StinkCageIndex = 261;
        OreSpawnConstants.TrooperEggIndex = 262;
        OreSpawnConstants.SpitEggIndex = 263;
        OreSpawnConstants.StinkEggIndex = 264;
        OreSpawnConstants.OstrichEggIndex = 265;
        OreSpawnConstants.GazelleEggIndex = 266;
        OreSpawnConstants.ChipmunkEggIndex = 267;
        OreSpawnConstants.CreepingHorrorCageIndex = 268;
        OreSpawnConstants.TerribleTerrorCageIndex = 269;
        OreSpawnConstants.CliffRacerCageIndex = 270;
        OreSpawnConstants.TriffidCageIndex = 271;
        OreSpawnConstants.PitchBlackCageIndex = 272;
        OreSpawnConstants.LurkingTerrorCageIndex = 273;
        OreSpawnConstants.CreepingHorrorEggIndex = 274;
        OreSpawnConstants.TerribleTerrorEggIndex = 275;
        OreSpawnConstants.CliffRacerEggIndex = 276;
        OreSpawnConstants.TriffidEggIndex = 277;
        OreSpawnConstants.PitchBlackEggIndex = 278;
        OreSpawnConstants.LurkingTerrorEggIndex = 279;
        OreSpawnConstants.GodzillaEggIndex = 280;
        OreSpawnConstants.WormSmallCageIndex = 281;
        OreSpawnConstants.WormMediumCageIndex = 282;
        OreSpawnConstants.WormLargeCageIndex = 283;
        OreSpawnConstants.CassowaryCageIndex = 284;
        OreSpawnConstants.CloudSharkCageIndex = 285;
        OreSpawnConstants.GoldFishCageIndex = 286;
        OreSpawnConstants.LeafMonsterCageIndex = 287;
        OreSpawnConstants.SmallWormEggIndex = 288;
        OreSpawnConstants.MediumWormEggIndex = 289;
        OreSpawnConstants.LargeWormEggIndex = 290;
        OreSpawnConstants.CassowaryEggIndex = 291;
        OreSpawnConstants.CloudSharkEggIndex = 292;
        OreSpawnConstants.GoldFishEggIndex = 293;
        OreSpawnConstants.LeafMonsterEggIndex = 294;
        OreSpawnConstants.TshirtEggIndex = 295;
        OreSpawnConstants.EnderKnightCageIndex = 296;
        OreSpawnConstants.EnderReaperCageIndex = 297;
        OreSpawnConstants.EnderKnightEggIndex = 298;
        OreSpawnConstants.EnderReaperEggIndex = 299;
        OreSpawnConstants.BeaverCageIndex = 300;
        OreSpawnConstants.BeaverEggIndex = 301;
        OreSpawnConstants.RotatorEggIndex = 302;
        OreSpawnConstants.VortexEggIndex = 303;
        OreSpawnConstants.PeacockEggIndex = 304;
        OreSpawnConstants.FairyEggIndex = 305;
        OreSpawnConstants.DungeonBeastEggIndex = 306;
        OreSpawnConstants.RatEggIndex = 307;
        OreSpawnConstants.FlounderEggIndex = 308;
        OreSpawnConstants.WhaleEggIndex = 309;
        OreSpawnConstants.IrukandjiEggIndex = 310;
        OreSpawnConstants.SkateEggIndex = 311;
        OreSpawnConstants.UrchinEggIndex = 312;
        OreSpawnConstants.RotatorCageIndex = 313;
        OreSpawnConstants.VortexCageIndex = 314;
        OreSpawnConstants.PeacockCageIndex = 315;
        OreSpawnConstants.FairyCageIndex = 316;
        OreSpawnConstants.DungeonBeastCageIndex = 317;
        OreSpawnConstants.RatCageIndex = 318;
        OreSpawnConstants.FlounderCageIndex = 319;
        OreSpawnConstants.WhaleCageIndex = 320;
        OreSpawnConstants.IrukandjiCageIndex = 321;
        OreSpawnConstants.SkateCageIndex = 322;
        OreSpawnConstants.UrchinCageIndex = 323;
        OreSpawnConstants.Robot1EggIndex = 324;
        OreSpawnConstants.Robot2EggIndex = 325;
        OreSpawnConstants.Robot3EggIndex = 326;
        OreSpawnConstants.Robot4EggIndex = 327;
        OreSpawnConstants.GhostEggIndex = 328;
        OreSpawnConstants.GhostSkellyEggIndex = 329;
        OreSpawnConstants.BrownAntEggIndex = 330;
        OreSpawnConstants.RedAntEggIndex = 331;
        OreSpawnConstants.RainbowAntEggIndex = 332;
        OreSpawnConstants.UnstableAntEggIndex = 333;
        OreSpawnConstants.TermiteEggIndex = 334;
        OreSpawnConstants.ButterflyEggIndex = 335;
        OreSpawnConstants.MothEggIndex = 336;
        OreSpawnConstants.MosquitoEggIndex = 337;
        OreSpawnConstants.FireflyEggIndex = 338;
        OreSpawnConstants.TRexEggIndex = 339;
        OreSpawnConstants.HerculesEggIndex = 340;
        OreSpawnConstants.MantisEggIndex = 341;
        OreSpawnConstants.StinkyEggIndex = 342;
        OreSpawnConstants.Robot5EggIndex = 343;
        OreSpawnConstants.CoinEggIndex = 344;
        OreSpawnConstants.TRexCageIndex = 345;
        OreSpawnConstants.HerculesCageIndex = 346;
        OreSpawnConstants.MantisCageIndex = 347;
        OreSpawnConstants.StinkyCageIndex = 348;
        OreSpawnConstants.BoyfriendEggIndex = 349;
        OreSpawnConstants.TheKingEggIndex = 350;
        OreSpawnConstants.ThePrinceEggIndex = 351;
        OreSpawnConstants.EasterBunnyEggIndex = 352;
        OreSpawnConstants.MolenoidEggIndex = 353;
        OreSpawnConstants.SeaMonsterEggIndex = 354;
        OreSpawnConstants.SeaViperEggIndex = 355;
        OreSpawnConstants.CaterKillerEggIndex = 356;
        OreSpawnConstants.LeonCageIndex = 357;
        OreSpawnConstants.LeonEggIndex = 358;
        OreSpawnConstants.HammerheadCageIndex = 359;
        OreSpawnConstants.HammerheadEggIndex = 360;
        OreSpawnConstants.RubberDuckyCageIndex = 361;
        OreSpawnConstants.RubberDuckyEggIndex = 362;
        OreSpawnConstants.CrystalCowEggIndex = 363;
        OreSpawnConstants.VillagerCowEggIndex = 364;
        OreSpawnConstants.CriminalEggIndex = 365;
        OreSpawnConstants.TheQueenEggIndex = 366;
        OreSpawnConstants.BrutalflyEggIndex = 367;
        OreSpawnConstants.NastysaurusEggIndex = 368;
        OreSpawnConstants.PointysaurusEggIndex = 369;
        OreSpawnConstants.CricketEggIndex = 370;
        OreSpawnConstants.ThePrincessEggIndex = 371;
        OreSpawnConstants.FrogEggIndex = 372;
        OreSpawnConstants.BrutalflyCageIndex = 373;
        OreSpawnConstants.NastysaurusCageIndex = 374;
        OreSpawnConstants.PointysaurusCageIndex = 375;
        OreSpawnConstants.CricketCageIndex = 376;
        OreSpawnConstants.FrogCageIndex = 377;
        OreSpawnConstants.JefferyEggIndex = 378;
        OreSpawnConstants.AntRobotEggIndex = 379;
        OreSpawnConstants.SpiderRobotEggIndex = 380;
        OreSpawnConstants.SpiderDriverEggIndex = 381;
        OreSpawnConstants.SpiderDriverCageIndex = 382;
        OreSpawnConstants.CrabEggIndex = 383;
        OreSpawnConstants.CrabCageIndex = 384;
    }
}
